name: Cypress Test

on:
  push: 
    branches:
      main

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:

      - name: Instalar Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb

      - run: npm install
      - run: npm run cy:run
