image: docker.io/cypress/browsers

name: Cypress Test

on:
  push: 
    branches:
      main

stages:
  - build


jobs:
  build-job:
    steps:
      stage: build
      script:
        - npm install
        - npm run cy:run
